### PR TITLE
External opt

### PR DESCRIPTION
**Pull request by philippeller**

### CODE REVIEW

**Comment by philippeller** [comment]
Because it saves a lot of complexity

**Comment by jllanfranchi** [comment]
okay, then remove references to it in the function calls

**Comment by philippeller** [comment]
Oh, good point, will do

**Comment by philippeller** [comment]
Found out "worst_idx" is not the same from argmax vs last element of argsort (when duplicates are present). hence some events reco'ed differently. It's a non-issue

**Pull request merged**
